vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet@1.2.3:7CBqCsMp6UjSKmG+LTaUGw==
    - vincaslt.highlight-matching-tag@0.9.5:DC1VJNcS1SBv9A94SBnOpg==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==